version: 2.1

orbs: 
  gcp-gcr: circleci/gcp-gcr@0.14.1
  gcp-gke: circleci/gcp-gke@1.4.0
  gcp-cli: circleci/gcp-cli@2.4.0
  terraform: circleci/terraform@3.0.1
  helm: circleci/helm@1.2.0

jobs:
  upgrade_helm_release:
    executor: gcp-gke/default
    steps:
      - checkout
      - gcp-cli/install:
          version: 376.0.0
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: primary
          perform-login: true
          install-kubectl: true
      - helm/upgrade-helm-chart:
          chart: ./test-app/deploy/chart
          helm-version: v3.8.0
          release-name: test-app
          namespace: test-app
          values-to-override: image.tag=$$CIRCLE_SHA1

workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraform
          path: tf-faceit
      - terraform/validate:
          checkout: true
          context: terraform
          attach-workspace: true
          path: tf-faceit
          requires:
            - terraform/fmt
      - terraform/plan:
          checkout: true
          context: terraform
          attach-workspace: true
          persist-workspace: true
          path: tf-faceit
          requires:
            - terraform/validate
      - approve_apply:
          type: approval
      - terraform/apply:
          attach-workspace: true
          context: terraform
          path: tf-faceit
          filters:
            branches:
              only: main
          requires:
            - terraform/plan
            - approve_apply
  build_push_deploy_test_app:
    jobs:
      - gcp-gcr/build-and-push-image:
          context: container-pusher
          docker-context: ./test-app
          path: ./test-app/build
          image: docker/test-app
          registry-url: europe-west1-docker.pkg.dev
          tag: $CIRCLE_SHA1
      - approve_deploy:
          type: approval
      - upgrade_helm_release:
          context: k8s-releaser
          requires: 
            - gcp-gcr/build-and-push-image
            - approve_deploy
      - gcp-gcr/add-image-tag:
          context: container-pusher
          image: docker/test-app
          registry-url: europe-west1-docker.pkg.dev
          source-tag: $CIRCLE_SHA1
          target-tag: latest
          requires: 
            - upgrade_helm_release